// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTKq0zIxvvD7mLGIefVDb79VTQOoHi1M8',
    appId: '1:533701055644:web:f10d7369a51bca08108959',
    messagingSenderId: '533701055644',
    projectId: 'ubiqa-production',
    authDomain: 'ubiqa-production.firebaseapp.com',
    storageBucket: 'ubiqa-production.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAY4Sz8aQ2kd9dYiSAhJFmuZLZRMs5fhE',
    appId: '1:533701055644:android:50b45aa18714297b108959',
    messagingSenderId: '533701055644',
    projectId: 'ubiqa-production',
    storageBucket: 'ubiqa-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS-Z4LlN0ZgYJVS1X4_qhomiqQhu3OBqo',
    appId: '1:533701055644:ios:b4d3a297fd65db46108959',
    messagingSenderId: '533701055644',
    projectId: 'ubiqa-production',
    storageBucket: 'ubiqa-production.firebasestorage.app',
    iosBundleId: 'com.jersondevs.ubiqa',
  );
}
